build:
 version: "1.0"
 
product:
 name: "Wealth Tracker Prod"
 version: "1.0"
 subProduct:
  - "Investment Tracker"
  - "Expense Tracker"
 info:
  developedBy: "abc"
  developedOn: "2026"
